version: '3.1'

services:
  finance-api-compose:
    image: eli/finance-api:0.0.1
    ports:
      - 18080:8080
    networks: 
      - finance-api
    depends_on: 
      - postgres-compose
  
  postgres-compose:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - APP_DB_USER=bycoders
      - APP_DB_PASS=f1n4nc3
      - APP_DB_NAME=finance
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 15432:5423
    networks: 
      - finance-api

networks:
  finance-api:
    driver: bridge


