version: '3.1'

services:
  postgres:
    container_name: postgres-13
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - APP_DB_USER=bycoders
      - APP_DB_PASS=f1n4nc3
      - APP_DB_NAME=finance
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432