CREATE TABLE TB_TRANSACTION
(
    TR_ID          SERIAL PRIMARY KEY,
    TR_DATE        DATE        NOT NULL,
    TR_VALUE       DECIMAL     NOT NULL,
    TR_CPF         VARCHAR(11) NOT NULL,
    TR_CREDIT_CARD VARCHAR(12) NOT NULL,
    TR_HOUR        TIMESTAMP   NOT NULL,
    FK_TP_ID       INT         NOT NULL,

    CONSTRAINT FK_TRANSACTION_TYPE
        FOREIGN KEY (FK_TP_ID)
            REFERENCES TB_TRANSACTION_TYPE (TP_ID) ON DELETE RESTRICT
)