CREATE TABLE TB_TRANSACTION_STORE
(
    TS_ID         SERIAL PRIMARY KEY,
    TS_STORE_NAME VARCHAR(100) NOT NULL,
    FK_OW_ID      INT          NOT NULL,
    CONSTRAINT FK_OWNER_ID
        FOREIGN KEY (FK_OW_ID)
            REFERENCES TB_OWNER (OW_ID) ON DELETE RESTRICT
)